### ISSUE TITLE
Vimeo video shows native and custom controls

### ISSUE THREAD

**Issue by stephan-strate** [thomaskieslich/tkmedia#2]
Videos that are added via Vimeo, show both native and your custom controls.
![vimeo_screen](https://user-images.githubusercontent.com/19595615/40124741-803c7bc4-5929-11e8-8ff5-2b50a1065ac2.PNG)

We are on your latest release [8.7.3](https://github.com/thomaskieslich/tkmedia/tree/8.7.3)
and Typo3 version 8.7.10
Is there a known way to fix this?

**Comment by thomaskieslich** [comment]
I think the best way would be to update plyr js and css.
