### ISSUE TITLE
Cover tab not showing

### ISSUE THREAD

**Issue by stephan-strate** [thomaskieslich/tkmedia#3]
Where can I find the "Cover" tab for local videos?
It does not show up for me.

We are on your latest release [8.7.3](https://github.com/thomaskieslich/tkmedia/tree/8.7.3)
and Typo3 version 8.7.10

**Comment by thomaskieslich** [comment]
Hi,
in the  Filelist the last tab should be Cover.

**Comment by stephan-strate** [comment]
Unfortunately, it did not show up.
Is there anything I need to configure for it to show up?

**Comment by thomaskieslich** [comment]
I had a look into the code and the sysext filemetadata must be loaded for this Feature. Could you try it?
